version: '3.5'

services:
  postgres:
    container_name: users-database
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: petproject
    ports:
      - "5432:5432"
    restart: unless-stopped